---

- name: ensure a list of packages installed
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
    allowerasing: true
  vars:
    packages:
      - bc
      - curl
      - fish
      - fuse
      - git
      - mosh
      - neovim
      - rsync
      - sudo
      - tmux
      - unzip
      - ripgrep

- name: install vim requirements
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
    allowerasing: true
  vars:
    packages:
      - gcc
      - gcc-c++

- name: install pyenv requirements
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
    allowerasing: true
  vars:
    packages:
      - gcc
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel

- name: install rbenv requirements
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
    allowerasing: true
  when: dotfiles_rbenv_install | bool
  vars:
    packages:
      - gcc
      - make
      - bzip2
      - openssl-devel
      - libyaml-devel
      - libffi-devel
      - readline-devel
      - zlib-devel
      - gdbm-devel
      - ncurses-devel
