---

- name: ensure a list of packages installed
  dnf:
    name: "{{ packages }}"
    state: present
    allowerasing: true
  vars:
    packages:
      - autoconf
      - automake
      - bc
      - bison
      - bzip2
      - bzip2-devel
      - cmake
      - curl
      - fuse
      - gcc
      - gcc-c++
      - git
      - glibc-devel
      - kernel-devel
      - libtool
      - make
      - mosh
      - openssl-devel
      - pkgconfig
      - platform-python-devel
      - readline-devel
      - rsync
      - sqlite
      - sqlite-devel
      - sudo
      - tmux
      - unzip
      - zlib-devel
      - zsh
