---
- name: enable fish repository
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo https://download.opensuse.org/repositories/shells:fish:release:3/CentOS-9_Stream/shells:fish:release:3.repo
  tags:
    - molecule-idempotence-notest

- name: ensure a list of packages installed
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
    allowerasing: true
  vars:
    packages:
      - bash
      - bc
      - curl
      - file
      - fish
      - fuse
      - git
      - kitty-terminfo
      - mosh
      - neovim
      - ripgrep
      - rsync
      - sudo
      - tmux
      - unzip

- name: install vim requirements
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
    allowerasing: true
  vars:
    packages:
      - gcc
      - gcc-c++

- name: install python requirements
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
    allowerasing: true
  vars:
    packages:
      - gcc
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
  when: dotfiles_rye_install | bool
